In [2]:
import numpy as np

## Concept #1: Override sub-array may affect parent array

In [10]:
arr = np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


sub-array is only an image of the parent array. Assign variable to this image and override values WILL affect parent array

In [5]:
sub_arr = arr[0:3] #It's NOT creating a new variable but rather a VIEW of the parent arr
print(sub_arr)

sub_arr[:] = 100 # If we overide evrything in sub_array with 100
print(sub_arr)

print(arr) #Notice the override actually changed the parent array and not just the sub array


[100 100 100]
[100 100 100]
[100 100 100   3   4   5   6   7   8   9  10]


To create a real subset not just a view, must use .copy()

In [12]:

sub_arr = arr[0:3].copy()
print(sub_arr)

sub_arr[:]=100
print(sub_arr)

print(arr)

[0 1 2]
[100 100 100]
[ 0  1  2  3  4  5  6  7  8  9 10]


## Concept #2: Division by zero does not cause error

In [14]:
arr = np.arange(0,11)

print(arr)
print(arr /0) #You get a runtime warning. code will contiune to run

#0/0 -> nan
# 2/0 -> inf

[ 0  1  2  3  4  5  6  7  8  9 10]
[nan inf inf inf inf inf inf inf inf inf inf]


C:\Users\JOHNC~1\AppData\Local\Temp/ipykernel_10112/2767405282.py:4: RuntimeWarning: divide by zero encountered in true_divide
  print(arr /0) #You get a runtime warning. code will contiune to run
C:\Users\JOHNC~1\AppData\Local\Temp/ipykernel_10112/2767405282.py:4: RuntimeWarning: invalid value encountered in true_divide
  print(arr /0) #You get a runtime warning. code will contiune to run
