In [2]:
import numpy as np

## Concept check: Real vs Image sub-array

In [3]:
arr = np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


### Image sub-array

In [4]:
sub_arr = arr[0:3] #It's NOT creating a new variable but rather a VIEW of the parent arr
print(sub_arr)

sub_arr[:] = 100 # If we overide evrything in sub_array with 100
print(sub_arr)

print(arr) #Notice the override actually changed the parent array and not just the sub array

#To create a real subset not just a view, you have to copy the parent array
arr_copy = arr.copy()

[0 1 2]
[100 100 100]
[100 100 100   3   4   5   6   7   8   9  10]
