# Numpy

A key usage of numpy is to convert arrays into vector/matrix for linear algebra calculation

In [2]:
import numpy as np

### Difference illustration

In [10]:
#Normal array
print(list(range(0,10)))

#Numpy Equvalent
print(np.arange(0,10)) 

#notice it turned into a vecor / [a matrix with 1 rows] - here is what it looks like in memory
np.arange(0,10)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
#Normal 2D array
mat =[[1,2,3],[4,5,6],[7,8,9]]
print(mat)

#np 2D array
np.array(mat)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### More examples of usings numpy

In [14]:
np.zeros(3)#vector of zeros

array([0., 0., 0.])

In [15]:
np.arange(0,10,2) #array with increatement of 2

array([0, 2, 4, 6, 8])

In [17]:
np.zeros((2,3))#pass in turples

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones(4)

array([1., 1., 1., 1.])

In [19]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.linspace(0,5,10) #this is NOT the same as arange(). It returns 1 dimension vector with 10 elements from 0 to 5 

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [24]:
np.eye(4) #create identify matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Generating random number via NP

In [26]:
np.random.rand(5)# there are bunch of ways to generate random number

array([0.06961165, 0.45562243, 0.48351825, 0.40052491, 0.97477432])

In [30]:
np.random.binomial(100,0.4) #x ~ BI(n,p)

50

In [31]:
np.random.randn(4,4)# 4x4 matrix from random normal distribution

array([[ 1.4006518 ,  0.64191449, -0.66936286,  2.19148112],
       [-1.70172035,  0.07637288,  0.57679621,  0.01943427],
       [-0.25152684,  1.73023792,  1.02974491, -0.64267848],
       [ 1.18406083, -0.65872578,  0.6722508 ,  1.22988006]])

In [32]:
np.random.randint(0,100)

68

In [43]:
ranarr = np.random.randint(0,50,10) #Generate 10 random numbers in range [0,49]
print(ranarr)
print(ranarr.max())
print(ranarr.min())
print(ranarr.argmax())#index of the max

[ 0 35 34 23  1 26 13 21 39 44]
44
0
9


In [47]:
arr = np.arange(0,25) #array of 25 numbers from 0 to 24
mat = arr.reshape(5,5) #reshape 1x25 matrix into 5x5
print(mat)
print(mat.shape)#get dimension of mat
print(mat.dtype)#get datatype of  mat

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
(5, 5)
int32


### Import specific function from numpy

In [48]:
from numpy.random import randint

#Then use randint() directly instead of "numpy.random.randint(0,10)"
randint(0,10)

### Indexing and Selection

In [5]:
arr = np.arange(0,11)
print(arr)


[ 0  1  2  3  4  5  6  7  8  9 10]


In [8]:
#Same as default array in python
arr[2]
#Recall default array syntax:
#lst = list(range(0,11))
#lst(2)

5
[0 1 2 3]


In [11]:
arr[0:4]

array([0, 1, 2, 3])

Override value in the array

In [15]:
arr[0:4] =100
print(arr)

[100 100 100 100   4   5   6   7   8   9  10]


#### Concept Check


In [19]:
arr = np.arange(0,11)
print(arr)

sub_arr = arr[0:3] #It's NOT creating a new variable but rather a VIEW of the parent arr
print(sub_arr)

sub_arr[:] = 100 # overide evrything in sub_array with 100
print(sub_arr)

print(arr) #the override actually changed the array itself not just the sub array

#To create a real subset not just a view, you have to copy the parent array
arr_copy = arr.copy()

[ 0  1  2  3  4  5  6  7  8  9 10]
[0 1 2]
[100 100 100]
[100 100 100   3   4   5   6   7   8   9  10]


In [28]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
#two ways to grab value in the 2D array
print(arr_2d[1][1])
print(arr_2d[1,1])

5
5


In [42]:
#grab subset of the 2d array
print(arr_2d[:2,1:])
print("  ")
print(arr_2d[1:,1:])

[[2 3]
 [5 6]]
  
[[5 6]
 [8 9]]


In [43]:
arr >5

array([ True,  True,  True, False, False, False,  True,  True,  True,
        True,  True])

### Conditional selction for matrix

In [48]:
arr = np.arange(0,11)
print(arr)

bool_arr = arr>3
print(bool_arr)

print(arr[arr>3])

[ 0  1  2  3  4  5  6  7  8  9 10]
[False False False False  True  True  True  True  True  True  True]
[ 4  5  6  7  8  9 10]


In [50]:
arr_2d = np.arange(50).reshape(5,10)

In [51]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [52]:
arr_2d[arr_2d>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
       40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [54]:
arr_2d[3:,8:]

array([[38, 39],
       [48, 49]])

In [55]:
arr_2d[2:4,4:6]

array([[24, 25],
       [34, 35]])

### np math operations

In [57]:
arr = np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [58]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [59]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [60]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [61]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [62]:
np.log(Arr)

NameError: name 'Arr' is not defined

In [63]:
np.log(arr)

C:\Users\JOHNC~1\AppData\Local\Temp/ipykernel_2108/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])